services:
  app:
    image: ghcr.io/miirage-exe/web-wii-app:main
    restart: unless-stopped
    networks:
      - proxy
    environment:
      TZ: "Europe/Paris"
    labels:
      traefik.enable: true
      traefik.http.routers.web-wii.rule: "Host(`web-wii.couseran.fr`)"

networks:
  proxy:
    external: true
